#!/bin/bash

function getport() {
        if [[ -f "$MCPATH/$servername/server.properties" ]]; then
                echo "$(grep '^server-port=' "$MCPATH/$1/server.properties" | cut -f 2 -d '=')"
        fi
}

