#!/bin/bash



function getport() {
        [[ "$#" -ne 1 ]] && {
                echoerr "too few arguments. Usage: getport <servername>"
                exit 1
        }
        if [[ -f "$MCPATH/$servername/server.properties" ]]; then
                echo "$(grep '^server-port=' "$MCPATH/$1/server.properties" | cut -f 2 -d '=')"
        fi
}

