#!/bin/bash



function getport() {
        [[ "$#" -ne 1 ]] && {
                echoerr "too few arguments. Usage: getport <servername>"
                exit 1
        }
        if [[ -f "$MCPATH/$servername/server.properties" ]]; then
                echo "$(grep '^server-port=' "$MCPATH/$1/server.properties" | cut -f 2 -d '=')"
        fi
}

function needscommand() {
        command -v "$1" >/dev/null 2>&1 || { echo >&2 "This script requires the command \"$1\" but it's not installed.  Aborting."; exit 1; }
}

