#!/bin/bash

source "$HOME/bin/_check" || { echo "error: $HOME/bin/_check not found or readable"; exit 1; }

servername="$1"

if [[ -z "$servername" ]]; then
	echoerr "too few arguments. Usage: attach <servername>"
	exit 1
else
	if "$HOME/bin/status" $1 &>/dev/null; then
		screen -r -S "mc-$servername"
	else
		echoerr "server $servername not found or offline"
	fi
fi
