#!/bin/bash

source "$HOME/bin/_check" || { echo "error: $HOME/bin/_check not found or readable"; exit 1; }

if [[ "$RUN_BY_CRON"  == "TRUE" ]]; then
	sleep $AUTOSTARTDELAY
fi

if [[ ! -f "$HOME/autostart.list" ]]; then
	echoerr "could not find $HOME/autostart.list"
	exit 1
fi

while read servername; do
	"$HOME/bin/start" "$servername" > /dev/null
done <"$HOME/autostart.list"
