#!/bin/bash

source "$HOME/bin/_check" || { echo "error: $HOME/bin/_check not found or readable"; exit 1; }

source "$HOME/minecraft.conf"

while read servername; do
	"$HOME/bin/start" "$servername"
done <"$HOME/autostart.list"
