#!/bin/bash

echo "autostart started at $(date)"

if [[ "$RUN_BY_CRON"  == "TRUE" ]]; then
	sleep 10
fi

source "$HOME/bin/_check" || { echo "error: $HOME/bin/_check not found or readable"; exit 1; }

if [[ ! -f "$HOME/autostart.list" ]]; then
	echoerr "could not find $HOME/autostart.list"
	exit 1
fi

while read servername; do
	"$HOME/bin/start" "$servername"
done <"$HOME/autostart.list"

