#!/bin/bash

# changes server configuration (via server.properties) with a text GUI

source "$HOME/bin/_check" || { echo "error: $HOME/bin/_check not found or readable"; exit 1; }

needscommand dialog

if [[ "$#" -lt 1 ]]; then
    echoerr "too few parameters. Usage: $0 <servername>"
    exit 1
fi

lines=$(($(tput lines)-6))
if [[ "$lines" -gt 40 ]]; then lines=40; fi
cols=$(($(tput cols)-6))
menuheight=$(($(tput lines)-13))
servername="$1"
xlabel=3
xitem=30
y=1 # incremental
tmprunfile=/tmp/jeffmc.config.run
tmpanswerfile=/tmp/jeffmc.config.answers
tmpkeysfile=/tmp/jeffmc.config.keys
key=
value=
flen=$((cols-xitem-xlabel-xlabel-xlabel))
#if [[ "$flen" -gt 80 ]]; then flen=80; fi
if [[ "$flen" -lt 10 ]]; then flen=10; fi
ilen=200
flensmall=6
ilensmall=5

function getlen() {
    if [[ "$key" == "op-permission-level" ]] \
    || [[ "$key" == "difficulty" ]]  \
    || [[ "$key" == "gamemode" ]]; then
        if [[ "$1" == "f" ]]; then echo "2"; else echo "1"; fi
    elif [[ "$key" == "max-world-size" ]]; then
        if [[ "$1" == "f" ]]; then echo "9"; else echo "8"; fi # mxa max-world-size is 29999984, so we dont need more than 8 digits
    elif [[ "$key" == "view-distance" ]]; then
        if [[ "$1" == "f" ]]; then echo "3"; else echo "2"; fi # max viewdistance is 15 (or something), so we dont need more than 2 digits
    elif [[ "$value" == "false" ]] \
    || [[ "$value" == "true" ]] \
    || [[ "$key" == "server-port" ]] \
    || [[ "$key" == "gamemode" ]] \
    || [[ "$key" == "max-players" ]] \
    || [[ "$key" == "player-idle-timeout" ]] \
    || [[ "$key" == "spawn-protection" ]]; then
        if [[ "$1" == "f" ]]; then echo "$flensmall"; else echo "$ilensmall"; fi
    else
        if [[ "$1" == "f" ]]; then echo "$flen"; else echo "$ilen"; fi
    fi
}

echo "debug 1"

cd "$MCPATH" || {
    echoerr "could not enter $MCPATH"
    exit 1
}

cd "$servername" || {
    echoerr "server $servername not found at $MCPATH/$servername"
    exit 1
}

if [[ ! -f server.properties ]]; then
    echoerr "could not find server.properties at $MCPATH/$servername."
    echoerr "did you start the server at least once?"
    exit 2
fi

array=""
touch $tmpkeysfile || {
    echoerr "could not create file $tmpkeysfile"
    exit 1
}
echo -n "" > $tmpkeysfile

echo "debug 2"

while read line; do
    if [[ ${line:0:1} != '#' ]]; then
        echo "debug 3 $key $value"
        key=$(echo $line | cut -f 1 -d '=')
        value=$(echo $line | cut -f 2 -d '=')
        #array="\"$key\" $y $xlabel \"$value\" $y $xitem $flen $ilen"
        array="$array \"$key\" $y $xlabel \"$value\" $y $xitem $(getlen f) $(getlen i)"
        echo $key >> $tmpkeysfile
        y=$((y+1))
    fi
done < server.properties

echo $array

touch $tmprunfile || {
    echoerr "could not create file $tmprunfile"
    exit 1
}

touch $tmpanswerfile || {
    echoerr "could not create file $tmpanswerfile"
    exit 1
}

echo -n "dialog --title \"JEFF-MC: Server configuration\" --form \"\\nServer: $servername\\nFile: server.properties\" $lines $cols $menuheight " > $tmprunfile 
echo -n $array >> $tmprunfile
echo -n " 2> $tmpanswerfile" >> $tmprunfile

cat $tmprunfile

bash $tmprunfile || exit
rm -f $tmprunfile

currentline=1 #incremental

mv server.properties server.properties.bak.$$ || { echoerr "could not rename server.properties"; exit 1; }
touch server.properties

while read line; do
    key=$line
    value=$(sed "${currentline}q;d" $tmpanswerfile)
    echo "${key}=${value}" >> server.properties
    currentline=$((currentline+1))
done < $tmpkeysfile
