#!/bin/bash

# changes server configuration (via server.properties) with a text GUI

source "$HOME/bin/_check" || { echo "error: $HOME/bin/_check not found or readable"; exit 1; }

needscommand dialog

if [[ "$#" -lt 1 ]]; then
    echoerr "too few parameters. Usage: $0 <servername>"
    exit 1
fi


lines=$(($(tput lines)-6))
cols=$(($(tput cols)-6))
#menuheight=$(($(tput lines)-6))
menuheight=45
servername="$1"
xlabel=3
xitem=30
y=1 # incremental
tmprunfile=/tmp/jeffmc.config.run

flen=$((cols-30))
ilen=200

cd "$MCPATH" || {
    echoerr "could not enter $MCPATH"
    exit 1
}

cd "$servername" || {
    echoerr "server $servername not found at $MCPATH/$servername"
    exit 1
}

if [[ ! -f server.properties ]]; then
    echoerr "could not find server.properties at $MCPATH/$servername."
    echoerr "did you start the server at least once?"
    exit 2
fi

array=""

while read line; do
    if [[ ${line:0:1} != '#' ]]; then
        key=$(echo $line | cut -f 1 -d '=')
        value=$(echo $line | cut -f 2 -d '=')
        #array="\"$key\" $y $xlabel \"$value\" $y $xitem $flen $ilen"
        array="$array \"$key\" $y $xlabel \"$value\" $y $xitem $flen $ilen"
        y=$((y+1))
    fi
done < server.properties

touch $tmprunfile || {
    echoerr "could not create file $tmprunfile"
    exit 1
}

echo -n "dialog --title \"JEFF-MC: Server configuration\" --form \"\\nCopyright 2018 JEFFmedia GbR\" $lines $cols $menuheight " > $tmprunfile 
echo -n $array >> $tmprunfile
#2>/tmp/jeffmc.$$


bash $tmprunfile
rm -f $tmprunfile


