#!/bin/bash

source "$HOME/bin/_check" || { echo "error: $HOME/bin/_check not found or readable"; exit 1; }

if [[ "$#" -lt 1 ]]; then
	echoerr "too few arguments. Usage: rmserver <servername>"
	exit 1
fi

if [[ ! -d "$MCPATH/$1" ]]; then
	echoerr "server $1 not found at $MCPATH/$1"
	exit 1
fi

read -p "Are you sure you want to completely remove server '$1'? [y/n]: " answer
if [[ "$answer" != "y" ]]; then
	echo "Aborting..."
	exit 1
else
	"$HOME/bin/status" $1 &>/dev/null
	if [[ "$?" -eq 0 ]]; then
		"$HOME/bin/stop" $1
	fi
	echo "Removing server $1 at $MCPATH/$1..."
	rm -rf "$MCPATH/$1/" || { echoerr "could not succesfully remove $MCPATH/$1"; exit 1; }
	echo "Server '$1' has been successfully removed"
	exit 0
fi
