#!/bin/bash

# Sendet einen Befehl an eine Serverkonsole
# Benutzung: send <servername> <befehl>

source "$HOME/bin/_check" || { echo "error: $HOME/bin/_check not found or readable"; exit 1; }

[[ "$#" -lt 2 ]] && {
	echoerr "too few parameters. Usage: send <servername> <command...>"
	exit 1
} 

if "$HOME/bin/status" $1 > /dev/null
then
	servername="$1"
	shift
	command="$*"
	screen -S mc-$servername -X stuff "${command}
" # newline, dont delete
else
	echoerr "server $1 is not online."
fi
