#!/bin/bash

# This script will try to shutdown all servers.

source "$HOME/bin/_check"

for servername in *; do
	if [[ -d "$MCPATH/$servername" ]]
	then
		if "$HOME/bin/status" $servername &> /dev/null
		then
			"$HOME/bin/stop" $servername
		fi
	fi
done
