#!/bin/bash

# timeout in seconds after when the server stop seems to have failed
# You can define a custom timeout in your $HOME/jeffmc.conf file or in each server's jeffmc-server.conf file.
TIMEOUT=120

source "$HOME/bin/_check" || { echo "error: $HOME/bin/_check not found or readable"; exit 1; }

[[ "$#" -lt 1 ]] && {
	echoerr "too few arguments. Usage: stop <servername>"
	exit 1
}

cd $MCPATH
cd "$1" || { echoerr "server $1 not found in $MCPATH/$1"; exit 1; }

"$HOME/bin/status" $1 &>/dev/null
if [[ "$?" -ne 0 ]]; then
	echoerr "server $1 not online (no session found in 'screen -ls')"
	exit 1
fi

# read the servers config for custom timeout
if [[ -f "$MCPATH/$1/jeffmc-server.conf" ]]; then
	source "$MCPATH/$1/jeffmc-server.conf" || {
		echoerr "could not parse server config file at $MCPATH/$1/jeffmc-server.conf"
		exit 1
	}
fi


screen -S "mc-$1" -X stuff 'stop\n'

echo -n "waiting up to $TIMEOUT seconds for server $1 to stop..."

try=0

while "$HOME/bin/status" $1 &> /dev/null
do
	echo -n "."
	sleep 1
	try=$((try+1))
	if [[ $try -gt $TIMEOUT ]]; then
		echo
		echoerr "could not stop server $1"
		exit 1
	fi
done
echo

echo "server $1 succesfully stopped in $try seconds"
